config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  get 'about' => 'pages#about'

  resources :tasks, except: [:new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Prefix    Verb   URI Pattern                Controller#Action
  # tasks     GET    /tasks(.:format)           tasks#index
  #           POST   /tasks(.:format)           tasks#create
  # new_task  GET    /tasks/new(.:format)       tasks#new
  # edit_task GET    /tasks/:id/edit(.:format)  tasks#edit
  # task      GET    /tasks/:id(.:format)       tasks#show
  #           PATCH  /tasks/:id(.:format)       tasks#update
  #           PUT    /tasks/:id(.:format)       tasks#update
  #           DELETE /tasks/:id(.:format)       tasks#destroy
  def index
    @tasks = Task.all.order(completed: :asc).order(id: :desc)
    @task = Task.new
    render :index
  end

  def create
    @new_task = Task.new(task_params)

    if @new_task.save
      redirect_to tasks_url
    else
      # Set error message
      redirect_to tasks_url
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
    render :edit
  end

  def update
    task = Task.find_by(id: params[:id])
    
    if task.nil?
        render plain: "Task doesn't exist", status: :unprocessable_entity
    elsif task.update(task_params)
        redirect_to tasks_url
    else
        render json: task.errors.full_messages, status: :unprocessable_entity
    end
end

  def destroy
    task = Task.find_by(id: params[:id])
        
    if task.nil?
        render plain: "Task doesn't exist", status: :unprocessable_entity
    elsif task.destroy
        redirect_to tasks_url
    else
        render json: user.errors.full_messages, status: :unprocessable_entity
    end
  end

  private
  def task_params
    params.require(:task).permit(:completed, :title, :details, :duedate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg_check_square
    data = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/></svg>'
    data.html_safe
  end
  
  def svg_square
    data = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/></svg>'
    data.html_safe
  end

  def svg_pencil_fill 
    data = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/></svg>'
    data.html_safe
  end

  def svg_trash_fill
    data = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/></svg>'
    data.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def link_to_completed(label, task, value)
    link_to(label, task_url(task, task: { completed: value }), method: :patch, )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/navbar" %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="d-flex justify-content-center align-items-center my-5">
  <div class="w-50 h-50 text-center">
      <h1 class="my-5">About</h1>
      <p class="lead">This is a simple todo list with one resource, viz. <b>tasks</b>, that implements all the CRUD operations: we can <b>create</b> new tasks, as well as <b>read</b>, <b>update</b> and <b>delete</b> the existing tasks.</p>
      <p class="lead">It was built with Ruby on Rails in the backend and Bootstrap for the CSS. You can find the source code in its repository at GitLab:</p>
      <p class="lead"><a href="https://gitlab.com/writeonlycode/rails-todo-list">https://gitlab.com/writeonlycode/rails-todo-list/</a></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_url %>">Tasks</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= about_url %>">About</a>
      </li>
    </ul>
  </div>
</nav>

app/views/tasks/edit.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">

  <div class="my-5">
    <%= bootstrap_form_with model: @task do |f| %>
      <%= f.text_field :title, placeholder: 'The title of your task' %>
      <%= f.text_area :details, placeholder: 'The details of your task', rows: 10 %>
      <%= f.date_field :duedate %>
      <%= f.submit 'Edit Task!' %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">

  <div class="my-5">
    <%= bootstrap_form_with model: @task, layout: :inline do |f| %>
      <%= f.text_field :title, placeholder: 'The title of your task', hide_label: true %>
      <%= f.text_field :details, placeholder: 'The details of your task', hide_label: true %>
      <%= f.date_field :duedate, hide_label: true %>
      <%= f.submit 'Create Task!' %>
    <% end %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th style="width: 1em"scope="col"></th>
        <th scope="col">Title</th>
        <th scope="col">Date</th>
        <th style="width: 4em" scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <!-- Completed Button -->
        <td>
          <%= task.completed ? link_to_completed(svg_check_square, task, false) : link_to_completed(svg_square, task, true) %>
        </td>

        <!-- Title and details -->
        <td <%= task.completed ? "class=text-decoration-line-through" : "" %>>
          <%= task.title %><br>
          <span class="font-size-xx-small"><%= task.details %></span>
        </td>

        <!-- Due Date -->
        <td class="text-nowrap <%= task.completed ? "text-decoration-line-through" : "" %>">
          <%= task.duedate.strftime("%B %-d, %Y") if task.duedate %>
        </td>

        <!-- Edit and Delete Buttons -->
        <td class="text-right">
          <%= link_to svg_pencil_fill, edit_task_url(task) %>
          <%= link_to svg_trash_fill, task_url(task), method: "delete" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>